/** Shared constants — categories, recipes, allergy labels. */
export const FRIDGE_CATS = { produce: 'Produce & herbs', dairy: 'Dairy', cheese: 'Cheese', eggs: 'Eggs', meat: 'Meat & poultry', seafood: 'Seafood', deli: 'Deli & prepared', leftovers: 'Leftovers', beverages: 'Beverages', condiments: 'Condiments & sauces', frozen: 'Frozen', baked: 'Bread & baked goods', snacks: 'Snacks' };
export const CAB_CATS = { grains: 'Grains & rice', pasta: 'Pasta & noodles', canned: 'Canned goods', spices: 'Spices & seasonings', snacks: 'Snacks', baking: 'Baking supplies', oils: 'Oils & vinegars', condiments: 'Condiments & sauces', beverages: 'Coffee & tea', dried: 'Dried goods & legumes' };
export const SHOP_CATS = { produce: 'Produce', dairy: 'Dairy', meat: 'Meat', pantry: 'Pantry', frozen: 'Frozen', beverages: 'Beverages', other: 'Other' };
export const CAT_BG = { produce: '#EAF3DE', dairy: '#E6F1FB', cheese: '#FAEEDA', eggs: '#FAEEDA', meat: '#F1EFE8', seafood: '#E6F1FB', deli: '#F1EFE8', leftovers: '#FAEEDA', beverages: '#E6F1FB', condiments: '#F1EFE8', frozen: '#E6F1FB', baked: '#FAEEDA', snacks: '#FAEEDA', grains: '#FAEEDA', pasta: '#FAEEDA', canned: '#FCEBEB', spices: '#FAEEDA', baking: '#FAEEDA', oils: '#EAF3DE', dried: '#EAF3DE' };
export const CAT_ICONS = { produce: '🌿', dairy: '🥛', cheese: '🧀', eggs: '🥚', meat: '🥩', seafood: '🐟', deli: '🥪', leftovers: '🍱', beverages: '🥤', condiments: '🫙', frozen: '🧊', baked: '🍞', snacks: '🍿', grains: '🍚', pasta: '🍝', canned: '🥫', spices: '🌶️', baking: '🧁', oils: '🫒', dried: '🫘' };
export const NEED_ALIASES = { spinach: ['spinach', 'greens', 'kale', 'lettuce'], egg: ['egg'], cheddar: ['cheddar', 'cheese'], yogurt: ['yogurt', 'yoghurt'], pasta: ['pasta', 'spaghetti', 'noodle', 'macaroni', 'leftover pasta'], butter: ['butter'], tomato: ['tomato'], chickpea: ['chickpea', 'chickpeas'], chicken: ['chicken', 'poultry'], rice: ['rice', 'basmati'] };
export const NAME_ICON_RULES = [[/cheese|cheddar|brie|gouda|mozzarella|parmesan|feta|swiss/i, '🧀'], [/^eggs?$|egg white|egg yolk/i, '🥚'], [/milk|cream(?!y)|half.and.half/i, '🥛'], [/yogurt|yoghurt|kefir/i, '🥛'], [/butter|margarine/i, '🧈'], [/chicken|turkey|poultry|drumstick/i, '🍗'], [/beef|steak|ground beef|mince(?!d garlic)/i, '🥩'], [/pork|bacon|sausage|ham|prosciutto/i, '🥓'], [/fish|salmon|tuna|cod|sardine/i, '🐟'], [/shrimp|prawn|shellfish|crab|lobster/i, '🦐'], [/spinach|mint|basil|cilantro|parsley|herb|kale|arugula|lettuce|greens|broccoli|carrot|celery|pepper|onion|garlic|ginger|cucumber|zucchini|vegetable|produce|sprout/i, '🌿'], [/apple|banana|berr|fruit|orange|lemon|lime|grape|melon|peach|mango/i, '🍎'], [/tomato/i, '🍅'], [/rice|basmati|jasmine rice/i, '🍚'], [/pasta|spaghetti|noodle|macaroni|linguine/i, '🍝'], [/bread|bagel|tortilla|bun|roll|croissant|muffin/i, '🍞'], [/soup|stew|broth/i, '🍲'], [/pizza/i, '🍕'], [/chocolate|candy|cookie|biscuit/i, '🍫'], [/coffee|espresso|tea|matcha/i, '☕'], [/juice|soda|water|drink|lemonade/i, '🥤'], [/chickpea|bean|lentil|pea/i, '🫘'], [/can|diced tomato|tomato paste/i, '🥫'], [/spice|paprika|cumin|oregano|thyme|seasoning|salt|peppercorn/i, '🌶️'], [/oil|vinegar|olive/i, '🫒'], [/honey|jam|syrup|marmalade/i, '🍯'], [/nut|almond|peanut|walnut|cashew/i, '🥜'], [/granola|oat|cereal/i, '🥣'], [/leftover/i, '🍱'], [/frozen|ice cream/i, '🧊']];
export const RECIPES = [
  { name: 'Spinach & cheese frittata', time: 20, tags: ['breakfast', 'vegetarian', 'glutenfree'], needs: ['spinach', 'egg', 'cheddar', 'yogurt'], desc: 'Whisk eggs with yogurt, fold in spinach and cheddar, then bake in a skillet until set and golden.', ingredients: [{ n: 'Baby spinach', a: '2 cups' }, { n: 'Eggs', a: '6 large' }, { n: 'Cheddar cheese', a: '100g grated' }, { n: 'Greek yogurt', a: '2 tbsp' }, { n: 'Onion', a: '1/2 diced' }] },
  { name: 'Creamy spinach pasta', time: 15, tags: ['lunch', 'dinner', 'vegetarian'], needs: ['spinach', 'cheddar', 'pasta', 'butter'], desc: 'Cook pasta, wilt spinach in garlic butter, stir in cheddar and a splash of pasta water for a quick creamy sauce.', ingredients: [{ n: 'Baby spinach', a: '3 cups' }, { n: 'Cheddar cheese', a: '80g grated' }, { n: 'Pasta', a: '250g cooked' }, { n: 'Garlic', a: '2 cloves' }, { n: 'Butter', a: '1 tbsp' }] },
  { name: 'Warm spinach dip', time: 10, tags: ['lunch', 'vegetarian', 'glutenfree', 'quick'], needs: ['yogurt', 'spinach', 'cheddar'], desc: 'Mix yogurt, melted cheddar and wilted spinach, warm gently and serve with crackers.', ingredients: [{ n: 'Greek yogurt', a: '1 cup' }, { n: 'Baby spinach', a: '2 cups' }, { n: 'Cheddar cheese', a: '120g' }, { n: 'Crackers', a: 'for serving' }] },
  { name: 'Tomato chickpea curry', time: 30, tags: ['dinner', 'vegetarian', 'glutenfree', 'dairyfree'], needs: ['tomato', 'chickpea', 'spinach'], desc: 'Simmer canned tomatoes and chickpeas with paprika, then stir in spinach until wilted.', ingredients: [{ n: 'Diced tomatoes', a: '2 cans' }, { n: 'Chickpeas', a: '1 can drained' }, { n: 'Baby spinach', a: '2 cups' }, { n: 'Paprika', a: '1 tsp' }, { n: 'Basmati rice', a: 'to serve' }] },
  { name: 'Yogurt chicken bowl', time: 25, tags: ['lunch', 'dinner', 'glutenfree'], needs: ['yogurt', 'chicken', 'rice'], desc: 'Marinate chicken in yogurt and spices, pan-sear until cooked through, serve over rice.', ingredients: [{ n: 'Chicken breast', a: '600g sliced' }, { n: 'Greek yogurt', a: '1/2 cup' }, { n: 'Basmati rice', a: '2 cups cooked' }, { n: 'Cucumber', a: '1/2 sliced' }] },
  { name: 'Spinach scrambled eggs', time: 8, tags: ['breakfast', 'vegetarian', 'glutenfree', 'quick'], needs: ['spinach', 'egg', 'butter'], desc: 'Sauté spinach in butter, pour in beaten eggs and scramble until softly set.', ingredients: [{ n: 'Baby spinach', a: '1 cup' }, { n: 'Eggs', a: '4 large' }, { n: 'Butter', a: '1 tbsp' }] },
  { name: 'Yogurt parfait', time: 5, tags: ['breakfast', 'dessert', 'vegetarian', 'glutenfree', 'quick'], needs: ['yogurt'], desc: 'Layer yogurt with granola and berries in a glass for a quick breakfast or snack.', ingredients: [{ n: 'Greek yogurt', a: '1 cup' }, { n: 'Granola', a: '1 crushed bar' }, { n: 'Berries', a: '1/2 cup' }] },
  { name: 'Cheese quesadilla', time: 12, tags: ['lunch', 'dinner', 'vegetarian', 'quick'], needs: ['cheddar'], desc: 'Fill tortillas with cheddar (and optional chicken), cook in a dry pan until cheese melts.', ingredients: [{ n: 'Cheddar cheese', a: '100g grated' }, { n: 'Tortilla', a: '2 large' }, { n: 'Chicken breast', a: '200g optional' }] },
  { name: 'Egg fried rice', time: 20, tags: ['lunch', 'dinner', 'glutenfree'], needs: ['egg', 'rice', 'spinach'], desc: 'Stir-fry day-old rice with scrambled eggs, spinach and soy sauce over high heat.', ingredients: [{ n: 'Eggs', a: '3 large' }, { n: 'Basmati rice', a: '3 cups cooked' }, { n: 'Baby spinach', a: '1 cup' }, { n: 'Soy sauce', a: '2 tbsp' }] },
  { name: 'Frozen yogurt bark', time: 10, tags: ['dessert', 'vegetarian', 'glutenfree'], needs: ['yogurt'], desc: 'Spread yogurt on a tray, drizzle honey, top with berries, freeze and break into pieces.', ingredients: [{ n: 'Greek yogurt', a: '2 cups' }, { n: 'Honey', a: '2 tbsp' }, { n: 'Berries', a: '1/2 cup' }] },
];
export const TIMING_CHOICES = ['1 day before', '2 days before', '3 days before', '5 days before', '1 week before'];
export const ALLERGY_LIST = ['Nuts', 'Peanuts', 'Dairy', 'Gluten', 'Shellfish', 'Eggs', 'Soy', 'Fish', 'Sesame', 'Meat'];
export const ALLERGY_LABELS = { nuts: 'Nuts', peanuts: 'Peanuts', dairy: 'Dairy', gluten: 'Gluten', shellfish: 'Shellfish', eggs: 'Eggs', soy: 'Soy', fish: 'Fish', sesame: 'Sesame', meat: 'Meat' };
export const EXPIRY = { SOON_DAYS: 7, ALERT_DAYS: 4 };
export function defaultUserDoc(email, displayName) {
  const now = new Date().toISOString();
  return { profile: { email, displayName, dateCreated: now, lastLogin: now, role: 'user' }, preferences: { dark: false, allergies: [], customRestrictions: [], notifications: { enabled: false, expiryReminders: true, recipeSuggestions: true, shoppingList: false, daysBefore: 3, quietHours: true, pushToken: null } }, settings: { shareAnalytics: true, personalizedRecipes: true, storeScanHistory: false, marketingEmails: false }, pantry: { fridge: [], cabinet: [] }, shoppingList: [], favorites: [] };
}
